id: P000419
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-16 15:38:59.133018
source_metadata:
  id: bdr:W1KG21818
  title: ནག་རྩིས་རྡེལ་འགྲེམ་འབྲས་བཤད།
  author: ''
  volumes:
    edb70f04df1243c2a9898a88fb476121:
      image_group_id: I1KG21886
      title: Volume 1 of nag rtsis rdel 'grem 'bras bshad/
      volume_number: 1
      total_pages: 200
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
